library = ".rv/library"

[project]
name = "prospectorDHSMadagascar"
r_version = "4.5.1"
repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest", force_source = true },
]
dependencies = [
    "devtools",
    "here",
    "tidyverse",
    "remotes",
    "rprojroot",
    "dplyr",
    "fledge",
    "pkgsite",
    "sf",
    "box",
    "skimr",
    "tarchetypes",
    "frictionless",
    "rmarkdown",
    "rstudioapi",
    "nanoparquet",
    "withr",
    "readxl",
    "languageserver",
    "janitor",
    "quarto",
    "rlang",
    "svglite",
    "usethis",
    "targets",
    "DiagrammeR",
    "readr",
    "codetools",
    "lubridate",
    "purrr",
    "later",
    "httpuv",
    "parsermd",
    "stringr",
    "tibble",
    "jsonlite",
    "websocket",
    "httpgd",
    "stringi",
    "rdhs",
    { name = "sess", git = "https://github.com/REditorSupport/vscode-R", branch = "master", directory = "sess" },
]
