project:
  type: default
  render:
    - "*.qmd"

format: gfm

filters:
  - sorting-hat
  - ripper

extensions:
  sorting-hat:
    keep:
      - r
    verbose: true

  ripper:
    include-yaml: false
    output-dir: "../R"
    script-links-position: "none"

execute:
  eval: false
