# WARNING - Generated by {fusen} from dev/flat_climate-diarrhea-analysis.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("climate_diarrhea_analysis works", {
  expect_true(inherits(climate_diarrhea_analysis, "function"))
})
