#!/usr/bin/env bash

# This script is used to activate the spack environment and set the necessary environment variables for R and other dependencies. It then executes the ARF command with any provided arguments.
spack env activate -d .
unset R_HOME

exec /usr/local/bin/arf "$@"