# WARNING - Generated by {fusen} from dev/flat_linking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Ingest the list of files in the project and return those that are flat DHS recode files
#' 
#' @param file_list Character vector of file paths to check.
#' @return Character vector of flat DHS recode file paths.
#' @export
#' @examples
#' link_inputs("config.yml") %>%
#'   list_raw_flat_dhs()
list_raw_flat_dhs <- function(file_list){
    
  # Filter the file list to include only flat DHS recode files
  flat_dhs_files <- stringr::str_subset(file_list, "MD(?:BR|HR|IR|PR|KR|CR|SQ|WI|MR|HW|FW)[0-9]{2}FL\\.[^.]+$")

  return(flat_dhs_files)
}
