# WARNING - Generated by {fusen} from dev/flat_load_dhs_data.Rmd: do not edit by hand # nolint: line_length_linter.

#' load_flat_dhs_data Title
#'
#' @return 1
#' @export
#'
#' @examples
#' ex_data <- here("data", "DHS Data", "DHS 1992", "MDIR21FL")
#' load_flat_dhs_data(ex_data) %>%
#'   tibble() %>%
#'   head()  
load_flat_dhs_data <- function(folder_path) {
  if (!dir.exists(folder_path)) {
    stop("Expected folder_path to be a directory, but got: ", folder_path, call. = FALSE)
  }

  files <- list.files(folder_path, full.names = FALSE)

  if (length(files) == 0) {
    stop("No files found in folder: ", folder_path, call. = FALSE)
  }

  temp_zip <- tempfile(fileext = ".zip")

  zip::zipr(
    zipfile = temp_zip,
    files = files,
    root = folder_path
  )

  if (!file.exists(temp_zip) || file.info(temp_zip)$size == 0) {
    stop("Failed to create zip for folder: ", folder_path, call. = FALSE)
  }

  rdhs:::read_dhs_flat(temp_zip)
}
